# Sample inference-only config for DNTextSpotter
# Inherit from the ViTAEv2 base configuration
_BASE_: "/root/DNTextSpotter/configs/ViTAEv2_S/Base_det.yaml"
VERSION: 2
# Only settings needed to run detection+text spotting

# Device to run inference on: "cpu" or "cuda"
MODEL:
  DEVICE: "cpu"
  # DEVICE: "cuda"
  WEIGHTS: "/root/DNTextSpotter/vitaev2_pretrain_tt_model_final.pth"
  # Enable transformer head and set inference threshold
  TRANSFORMER:
    ENABLED: True
    INFERENCE_TH_TEST: 0.4

# Dataset(s) for evaluation/inference (used by MetadataCatalog)
# Replace "my_test_dataset" with the name you registered
DATASETS:
  TEST: ("totaltext_test",)

# Input settings for inference
INPUT:
  # Shorter side at least this long (longer side capped by MAX_SIZE_TEST)
  MIN_SIZE_TEST: 1024
  # Longer side at most this long
  MAX_SIZE_TEST: 1892

# Simple default settings for inference
TEST:
  # Enable Test-Time Augmentation? (usually False for speed)
  AUG:
    ENABLED: False

# Lexicon-constrained CTC configuration
LEXICON:
  # Type of lexicon constraint: "none" (standard CTC) or "custom" (from file)
  # TYPE: "custom"
  TYPE: "none"
  # Path to custom lexicon file (one word per line)
  FILE: "tire_lexicon.txt"
  # Similarity threshold for lexicon matching (0.0-1.0)
  THRESHOLD: 0.5

  # Glob or directory path for inference images (overrides CLI)
INFERENCE:
  # INPUT_GLOB: "/mnt/d/minyeong/LTR/clahe/*.jpg" 
  # "C:\Users\HANTA\Desktop\minyeong\LTR\ltr_rotation_imgs\20250103_1009_KT235_65R16C_10RA18_LBEFHK\center_img.jpg"
  INPUT_GLOB: "/mnt/c/Users/HANTA/Desktop/minyeong/LTR/ltr_rotation_imgs/*/*.jpg"
  # INPUT_GLOB: "/mnt/d/minyeong/LTR/clahe/20250116_1926_KT235_65R16C_10RA18_LBEFHK_1.jpg"
  # 20250116_1926_KT235_65R16C_10RA18_LBEFHK_1
  # INPUT_GLOB: "/home/hanta/minyeong/DNTextSpotter/outputs/블로그1.jpg"
  OUTPUT_DIR: "/mnt/c/Users/HANTA/Desktop/minyeong/LTR/rotation_inference_results"


# python tools/inference.py --config-file configs/inference_sample.yaml
# python tools/inference_all.py --config-file configs/inference_sample.yaml